### ISSUE TITLE
Add gnome-shell connector

### ISSUE THREAD

**Issue by bristow** [simbd/Ubuntu_20.04LTS_PostInstall#1]
In order to install GS extensions, we need to do that :

`sudo apt install chrome-gnome-shell`

It would be useful to add it to the script, thanks !

Doc : https://wiki.gnome.org/Projects/GnomeShellIntegrationForChrome/Installation

**Comment by simbd** [comment]
J'avais déjà intégré ce paquet dans le pack d'extension ici  : 
https://github.com/simbd/Ubuntu_20.04LTS_PostInstall/blob/master/Postinstall_Ubuntu-20.04LTS_FocalFossa.sh#L534

Après je peux toujours l'ajouter dans le choix "Supplément pour Gnome" au début au cas ou le pack d'extension ne serai pas choisi.

Sache que ce paquet n'est utile que pour installer des extensions directement depuis le site officiel des extensions (extensions.gnome.org) mais tu peux aussi installer des extensions depuis le dépôt d'Ubuntu qui en contient plusieurs dizaines et dans ce cas tu as juste à faire un "apt install gnome-shell-extension-.....".

**Comment by simbd** [comment]
Je viens de l'ajouter dans le choix "Gnome Supplément" => https://github.com/simbd/Ubuntu_20.04LTS_PostInstall/blob/master/Postinstall_Ubuntu-20.04LTS_FocalFossa.sh#L36

**Comment by bristow** [comment]
Thanks !
