### ISSUE TITLE
Portabilité - Detection shell

### ISSUE THREAD

**Issue by Barikad** [simbd/Ubuntu_20.04LTS_PostInstall#3]
Le shebang précise bien /bin/bash, mais si on lance le script comme celà:
`sh Postinstall_Ubuntu-20.04LTS_FocalFossa.sh`
Ce sera alors le shell par défaut qui sera utilisé (zsh par exemple). Hors le script utilise certaines fonction non portables, ce qui va provoquer des erreur, et ce aprés la selection des logiciels.
Une des solutions pourrait être de verifier le shell qui s'execute et mettre un avertissement.

**Comment by simbd** [comment]
Bonjour,
Effectivement ce script est fait pour Bash et non autre chose comme Zsh, je vais le préciser dans la documentation.

Si vous avez la ligne de code à mettre pour la détection du shell, vous pouvez me l'indiquer afin que je l'ajoute dans une condition "if" pour pouvoir mettre l'avertissement.

**Comment by simbd** [comment]
Rejeté => Le script est clairement indiqué pour bash, à l'utilisateur de ne pas utiliser un autre shell.
