### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by fredericpetitdev** [simbd/Ubuntu_20.04LTS_PostInstall#5]
Bonsoir :) Il peut arriver d'être derrière un proxy et donc celui-ci doit être configuré avant toute tentative de téléchargement. Il serait adéquat de lancer avant les choix, une fenêtre demandant si l'on veut utiliser un proxy et pouvoir y renseigner graphiquement l'adresse et le port, et lancer un `export http_proxy='ip:port'`. Cdlt :)

**Comment by simbd** [comment]
Rejeté => trop complexe à mettre en place directement dans le script et il est facile de configurer un proxy avant de lancer le script (faisable directement dans l'environnement graphique).
