### ISSUE TITLE
How can I define my own set of stuff to be installed ?

### ISSUE THREAD

**Issue by HerKa2** [simbd/Ubuntu_20.04LTS_PostInstall#6]
Hi there !
Nice job you have made.
How can I define my own set of stuff to be installed ? I need an alternate configuration to the one you have predefined.
Rgs.
H.

**Comment by simbd** [comment]
Bonjour,

Très simple : les choix cochés avec l'option "par défaut" correspondent au fichier "Zenity_default_choice.sh".

- Mettre à "TRUE" si vous voulez que la case soit coché pour le logiciel par défaut
- Mettre à "FALSE" si vous voulez que la case soit décoché.

exemple : Pour que Pidgin soit décoché  :   
$(chkDef "FALSE") "$CA_PIDGIN" "$CD_PIDGIN" \
